version: '3'
services:
  database:
    image: postgres:9.6
    restart: always
    ports:
      - "5433:5432"
    networks:
      - prisma-dev
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: prisma
  prisma:
    image: prismagraphql/prisma:1.34.6
    restart: always
    depends_on:
      - database
    networks:
      - prisma-dev
    ports:
    - "4467:4467"
    environment:
      PRISMA_CONFIG: |
        port: 4467
        # managementApiSecret: my-secret
        databases:
          default:
            connector: postgres
            active: true
            host: database
            database: postgres
            port: 5432
            user: postgres
            password: prisma
            queueSize: 10000
networks:
  prisma-dev:
    driver: bridge